'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Hammer, Plus, Trash2 } from 'lucide-react'
import { formatCurrency } from '@/lib/utils'
import { toast } from '@/components/ui/use-toast'

interface EstimateItem {
  id: string
  name: string
  quantity: number
  unit: string
  unitPrice: number
  totalPrice: number
}

export default function EstimatorPage() {
  const [items, setItems] = useState<EstimateItem[]>([])
  const [newItem, setNewItem] = useState({
    name: '',
    quantity: 1,
    unit: 'bag',
    unitPrice: 0,
  })
  const [estimateName, setEstimateName] = useState('')

  const addItem = () => {
    if (!newItem.name || newItem.unitPrice <= 0) return

    const item: EstimateItem = {
      id: Date.now().toString(),
      ...newItem,
      totalPrice: newItem.quantity * newItem.unitPrice,
    }

    setItems([...items, item])
    setNewItem({ name: '', quantity: 1, unit: 'bag', unitPrice: 0 })
  }

  const removeItem = (id: string) => {
    setItems(items.filter((item) => item.id !== id))
  }

  const totalCost = items.reduce((sum, item) => sum + item.totalPrice, 0)

  const saveEstimate = async () => {
    if (items.length === 0) {
      toast({
        title: 'Error',
        description: 'Please add at least one material to save',
      })
      return
    }

    try {
      const response = await fetch('/api/estimates', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: estimateName || `Estimate ${new Date().toLocaleDateString()}`,
          items: items,
          totalCost: totalCost,
        }),
      })

      if (!response.ok) {
        toast({
          title: 'Error',
          description: 'Failed to save estimate. Please try again.',
        })
        return
      }

      toast({
        title: 'Success',
        description: 'Estimate saved successfully!',
      })
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to save estimate. Please try again.',
      })
    }
  }

  const exportToPDF = () => {
    if (items.length === 0) {
      toast({
        title: 'Error',
        description: 'Please add at least one material to export',
      })
      return
    }

    // Create printable content
    const printContent = `
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <title>Material Cost Estimate - Wandura</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background-color: #f5f5f5; }
            .total { font-size: 1.2em; font-weight: bold; margin-top: 20px; }
            .footer { margin-top: 40px; color: #666; font-size: 0.9em; }
          </style>
        </head>
        <body>
          <h1>Material Cost Estimate</h1>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          ${estimateName ? `<p><strong>Project:</strong> ${estimateName}</p>` : ''}
          <table>
            <thead>
              <tr>
                <th>Material</th>
                <th>Quantity</th>
                <th>Unit</th>
                <th>Unit Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              ${items.map(item => `
                <tr>
                  <td>${item.name}</td>
                  <td>${item.quantity}</td>
                  <td>${item.unit}</td>
                  <td>$${item.unitPrice.toFixed(2)}</td>
                  <td>$${item.totalPrice.toFixed(2)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="total">
            <p>Total Estimated Cost: $${totalCost.toFixed(2)}</p>
          </div>
          <div class="footer">
            <p>Generated by Wandura - Skilled Labor On-Demand</p>
            <p>This is an estimate only. Actual costs may vary.</p>
          </div>
        </body>
      </html>
    `

    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(printContent)
      printWindow.document.close()
      printWindow.print()
    }

    toast({
      title: 'Export Ready',
      description: 'Your estimate has been prepared for printing/saving as PDF',
    })
  }

  const clearAll = () => {
    setItems([])
    setEstimateName('')
    toast({
      title: 'Cleared',
      description: 'All materials have been removed',
    })
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 border-b">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Hammer className="h-6 w-6 text-primary" />
            <span className="text-xl font-bold">Wandura</span>
          </Link>
          <Button asChild>
            <Link href="/dashboard">Dashboard</Link>
          </Button>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-8">Material Cost Estimator</h1>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Add Item Form */}
          <Card>
            <CardHeader>
              <CardTitle>Add Material</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Label htmlFor="name">Material Name</Label>
                <Input
                  id="name"
                  placeholder="e.g., Portland Cement"
                  value={newItem.name}
                  onChange={(e) => setNewItem({ ...newItem, name: e.target.value })}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="quantity">Quantity</Label>
                  <Input
                    id="quantity"
                    type="number"
                    min="1"
                    value={newItem.quantity}
                    onChange={(e) =>
                      setNewItem({ ...newItem, quantity: parseFloat(e.target.value) || 1 })
                    }
                  />
                </div>
                <div>
                  <Label htmlFor="unit">Unit</Label>
                  <Input
                    id="unit"
                    placeholder="e.g., bag, ton, piece"
                    value={newItem.unit}
                    onChange={(e) => setNewItem({ ...newItem, unit: e.target.value })}
                  />
                </div>
              </div>
              <div>
                <Label htmlFor="price">Unit Price ($)</Label>
                <Input
                  id="price"
                  type="number"
                  min="0"
                  step="0.01"
                  value={newItem.unitPrice || ''}
                  onChange={(e) =>
                    setNewItem({ ...newItem, unitPrice: parseFloat(e.target.value) || 0 })
                  }
                />
              </div>
              <Button onClick={addItem} className="w-full">
                <Plus className="h-4 w-4 mr-2" />
                Add Material
              </Button>
            </CardContent>
          </Card>

          {/* Estimate Summary */}
          <Card>
            <CardHeader>
              <CardTitle>Estimate Summary</CardTitle>
            </CardHeader>
            <CardContent>
              {items.length === 0 ? (
                <p className="text-center text-muted-foreground py-8">
                  No materials added yet
                </p>
              ) : (
                <>
                  <div className="space-y-3 mb-6">
                    {items.map((item) => (
                      <div
                        key={item.id}
                        className="flex items-start justify-between border-b pb-3"
                      >
                        <div className="flex-1">
                          <p className="font-medium">{item.name}</p>
                          <p className="text-sm text-muted-foreground">
                            {item.quantity} {item.unit} × {formatCurrency(item.unitPrice)}
                          </p>
                        </div>
                        <div className="flex items-center gap-2">
                          <span className="font-semibold">
                            {formatCurrency(item.totalPrice)}
                          </span>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => removeItem(item.id)}
                          >
                            <Trash2 className="h-4 w-4 text-destructive" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="border-t pt-4">
                    <div className="flex justify-between items-center text-lg font-bold">
                      <span>Total Estimated Cost:</span>
                      <span className="text-2xl text-primary">
                        {formatCurrency(totalCost)}
                      </span>
                    </div>
                  </div>

                  <div className="mt-6 space-y-2">
                    <div className="flex gap-2">
                      <Button variant="outline" className="flex-1" onClick={saveEstimate}>
                        Save Estimate
                      </Button>
                      <Button variant="outline" className="flex-1" onClick={exportToPDF}>
                        Export to PDF
                      </Button>
                    </div>
                    <div className="flex gap-2">
                      <Button className="flex-1" asChild>
                        <Link href="/stores">Order Materials</Link>
                      </Button>
                      <Button variant="destructive" onClick={clearAll}>
                        Clear All
                      </Button>
                    </div>
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Common Materials Reference */}
        <Card className="mt-8">
          <CardHeader>
            <CardTitle>Common Construction Materials</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-3 gap-4">
              {[
                { name: 'Portland Cement', unit: 'bag', price: 12.99 },
                { name: 'River Sand', unit: 'ton', price: 45.0 },
                { name: 'Gravel', unit: 'ton', price: 38.0 },
                { name: 'Concrete Blocks', unit: 'piece', price: 2.25 },
                { name: 'Ceramic Tiles', unit: 'box', price: 28.5 },
                { name: 'Steel Rebar #4', unit: 'piece', price: 8.75 },
              ].map((material) => (
                <div
                  key={material.name}
                  className="p-3 border rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer"
                  onClick={() =>
                    setNewItem({
                      name: material.name,
                      quantity: 1,
                      unit: material.unit,
                      unitPrice: material.price,
                    })
                  }
                >
                  <p className="font-medium">{material.name}</p>
                  <p className="text-sm text-muted-foreground">
                    {formatCurrency(material.price)}/{material.unit}
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
